### ISSUE TITLE
how to eject a react project for cordova 

### ISSUE THREAD

**Issue by ahmedrowaihi** [dilanx/craco#287]
After Ejecting the react app I am not able to build it

yarn run v1.22.5
$ craco build
node:internal/modules/cjs/loader:940
  const err = new Error(message);
              ^

Error: Cannot find module 'react-scripts\package.json'
Require stack:
- C:\Users\USER\Desktop\customerapp\node_modules\@craco\craco\lib\cra.js
- C:\Users\USER\Desktop\customerapp\node_modules\@craco\craco\scripts\build.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at Function.resolve (node:internal/modules/cjs/helpers:99:19)
    at resolvePackageJson (C:\Users\USER\Desktop\customerapp\node_modules\@craco\craco\lib\cra.js:42:20)
    at getReactScriptVersion (C:\Users\USER\Desktop\customerapp\node_modules\@craco\craco\lib\cra.js:46:40)
    at validateCraVersion (C:\Users\USER\Desktop\customerapp\node_modules\@craco\craco\lib\validate-cra-version.js:4:38)
    at C:\Users\USER\Desktop\customerapp\node_modules\@craco\craco\scripts\build.js:22:5 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\USER\\Desktop\\customerapp\\node_modules\\@craco\\craco\\lib\\cra.js',
    'C:\\Users\\USER\\Desktop\\customerapp\\node_modules\\@craco\\craco\\scripts\\build.js'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by Dakkers** [comment]
if you're ejecting from CRA you shouldn't need Craco

**Comment by ahmedrowaihi** [comment]
I just built my App on React Native, No more cordova craps
