### ISSUE TITLE
craco.config.ts: must use import to load ES module ... but already using import statement

### ISSUE THREAD

**Issue by thediveo** [dilanx/craco#408]
Using CRACO on a CRA 4.x React application, I need to configure `@mdx-js/loader` to use rehype plugins, and `rehype-slug` in particular. Now, rehype-slug's documentation says that I need to "import" this module.

If this isn't the proper place to ask for help, then please advice me where to ask instead.

As `require.resolve("rehype-slug")` fails with `Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: ...` I tried to switch to a `craco.config.ts` and import rehype-slug. This is my `craco.config.ts`:

```ts
import { addAfterLoader, loaderByName } from '@craco/craco'
import slug from 'rehype-slug'

const config = {
    webpack: {
        configure: (webpackConfig) => {
            addAfterLoader(webpackConfig, loaderByName('babel-loader'), {
                test: /\.(md|mdx)$/,
                loader: '@mdx-js/loader',
                options: {
                    rehypePlugins: [
                        slug,
                    ],
                },
            })
            return webpackConfig
        }
    }
}

export default config
```

This also fails in line 2, where the `import` statement is:

```
UnhandledPromiseRejectionWarning: Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: lxkns/web/lxkns/node_modules/rehype-slug/index.js
require() of ES modules is not supported.
require() of lxkns/web/lxkns/node_modules/rehype-slug/index.js from lxkns/web/lxkns/craco.config.ts is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from lxkns/web/lxkns/node_modules/rehype-slug/package.json.

    at new NodeError (internal/errors.js:322:7)
[...]
    at Object.<anonymous> (/home/harald/github/lxkns/web/lxkns/craco.config.ts:2:1)
```

What stupid mistake am I doing here?

`package.json` has **no** `type` property setting.

`tsconfig.json` if that might give any clue as to what my error is:

```
{
  "compilerOptions": {
    "target": "es2020",
    "downlevelIteration": true,
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": false,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "react-jsx",
    "noEmit": true,
    "baseUrl": "src",
    "noFallthroughCasesInSwitch": false,
    "types": [
      "cypress",
      "cypress-react-selector",
      "cypress-react-router"
    ],
  },
  "include": [
    "src/",
    "styleguidist/"
  ]
}
```

**Comment by dilanx** [comment]
@thediveo would it be possible to create a demo repo where this issue is reproduced (or perhaps share your package.json so I can try recreating the issue)?

**Comment by thediveo** [comment]
will do

**Comment by hsbtr** [comment]
I also encountered this problem

**Comment by davetapley** [comment]
@dilanx repro here: https://github.com/JEFuller/craco-408-repro

```
nvm use 22.12.0
npm i
npm run build
craco build
```

```
> react-craco-typescript-app@0.1.0 build
> 
/Users/dave/code/jefuller/craco-408-repro/node_modules/ts-node/dist-raw/node-internal-errors.js:46
  const err = new Error(getErrRequireEsmMessage(filename, parentPath, packageJsonPath))
              ^
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/dave/code/jefuller/craco-408-repro/craco.config.ts
require() of ES modules is not supported.
require() of /Users/dave/code/jefuller/craco-408-repro/craco.config.ts from /Users/dave/code/jefuller/craco-408-repro/node_modules/cosmiconfig-typescript-loader/dist/loader.js is an ES module file as it is a .ts file whose nearest parent package.json contains "type": "module" which defines all .ts files in that package scope as ES modules.
Instead change the requiring code to use import(), or remove "type": "module" from /Users/dave/code/jefuller/craco-408-repro/package.json.

    at createErrRequireEsm (/Users/dave/code/jefuller/craco-408-repro/node_modules/ts-node/dist-raw/node-internal-errors.js:46:15)
    at assertScriptCanLoadAsCJSImpl (/Users/dave/code/jefuller/craco-408-repro/node_modules/ts-node/dist-raw/node-internal-modules-cjs-loader.js:584:11)
    at Object.require.extensions.<computed> [as .ts] (/Users/dave/code/jefuller/craco-408-repro/node_modules/ts-node/src/index.ts:1610:5)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:219:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:138:16)
    at /Users/dave/code/jefuller/craco-408-repro/node_modules/cosmiconfig-typescript-loader/dist/loader.js:11:28 {
  name: 'TypeScriptCompileError'
}
```

**Comment by thediveo** [comment]
I've moved on to vite.js

**Comment by davetapley** [comment]
@dilanx do you want this reopened, or shall I create a new issue?
