### ISSUE TITLE
Unable to use babel-loader in craco@7 alpha

### ISSUE THREAD

**Issue by JeffBaumgardt** [dilanx/craco#444]
I am testing out attempting to change out the babel-loader for esbuild-loader. I am running CRA 5 so I am on `"@craco/craco": "^7.0.0-alpha.7"`. Attempting to use the following config I get a error trying to load the babel-loader as a plugin.

* craco.config.js
```js
const {
  addAfterLoader,
  removeLoaders,
  loaderByName,
  getLoaders,
  throwUnexpectedConfigError,
} = require("@craco/craco");
const { ESBuildMinifyPlugin } = require("esbuild-loader");

const throwError = (message) =>
  throwUnexpectedConfigError({
    packageName: "craco",
    githubRepo: "gsoft-inc/craco",
    message,
    githubIssueQuery: "webpack",
  });

module.exports = {
  webpack: {
    configure: (webpackConfig, { paths }) => {
      const { hasFoundAny, matches } = getLoaders(
        webpackConfig,
        loaderByName("babel-loader")
      );
      if (!hasFoundAny) throwError("failed to find babel-loader");

      console.log("removing babel-loader");
      const { hasRemovedAny, removedCount } = removeLoaders(
        webpackConfig,
        loaderByName("babel-loader")
      );
      if (!hasRemovedAny) throwError("no babel-loader to remove");
      if (removedCount !== 2)
        throwError("had expected to remove 2 babel loader instances");

      console.log("adding esbuild-loader");

      const tsLoader = {
        test: /\.(js|mjs|jsx|ts|tsx)$/,
        include: paths.appSrc,
        loader: require.resolve("esbuild-loader"),
        options: {
          loader: "tsx",
          target: "es2015",
        },
      };

      const { isAdded: tsLoaderIsAdded } = addAfterLoader(
        webpackConfig,
        loaderByName("url-loader"),
        tsLoader
      );
      if (!tsLoaderIsAdded) throwError("failed to add esbuild-loader");
      console.log("added esbuild-loader");

      console.log("adding non-application JS babel-loader back");
      const { isAdded: babelLoaderIsAdded } = addAfterLoader(
        webpackConfig,
        loaderByName("esbuild-loader"),
        matches[1].loader // babel-loader
      );
      if (!babelLoaderIsAdded)
        throwError("failed to add back babel-loader for non-application JS");
      console.log("added non-application JS babel-loader back");

      console.log("replacing TerserPlugin with ESBuildMinifyPlugin");
      webpackConfig.optimization.minimizer = [
        new ESBuildMinifyPlugin({
          target: "es2015",
        }),
      ];

      return webpackConfig;
    },
  },
};

```

I installed on a brand new fresh install of CRA v5.0.1

```json
{
  "name": "craco-esbuild-test",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^13.3.0",
    "@testing-library/user-event": "^13.5.0",
    "@types/jest": "^27.5.2",
    "@types/node": "^16.11.47",
    "@types/react": "^18.0.17",
    "@types/react-dom": "^18.0.6",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1",
    "typescript": "^4.7.4",
    "web-vitals": "^2.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "craco build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@craco/craco": "^7.0.0-alpha.7",
    "esbuild-loader": "^2.19.0"
  }
}
```

The cli error is
```
~/temp/craco-esbuild-test  master ✗                                      2m ⚑
▶ time npm run build
npm does not support Node.js v15.14.0
You should probably upgrade to a newer version of node as we
can't make any promises that npm will work with this version.
You can find the latest version at https://nodejs.org/
npm WARN config init.author.name Use `--init-author-name` instead.
npm WARN config init.author.email Use `--init-author-email` instead.
npm WARN config init.author.url Use `--init-author-url` instead.

> craco-esbuild-test@0.1.0 build
> craco build

removing babel-loader⠇ : timing config:load:flatten Completed in 3ms
adding esbuild-loader
/Users/jeffbaumgardt/temp/craco-esbuild-test/node_modules/@craco/craco/dist/lib/plugin-utils.js:28
    throw new Error("".concat(message, "\n\n") +
          ^
Error: failed to add esbuild-loader

This error probably occurred because you updated react-scripts or craco. Please try updating craco to the latest version:

   $ yarn upgrade craco

Or:

   $ npm update craco

If that doesn't work, craco needs to be fixed to support the latest version.
Please check to see if there's already an issue in the gsoft-inc/craco repo:

   * https://github.com/gsoft-inc/craco/issues?q=is%3Aissue+webpack

If not, please open an issue and we'll take a look. (Or you can send a PR!)

You might also want to look for related issues in the craco and create-react-app repos:

   * https://github.com/sharegate/craco/issues?q=is%3Aissue+webpack
   * https://github.com/facebook/create-react-app/issues?q=is%3Aissue+webpack

    at throwUnexpectedConfigError (/Users/jeffbaumgardt/temp/craco-esbuild-test/node_modules/@craco/craco/dist/lib/plugin-utils.js:28:11)
    at throwError (/Users/jeffbaumgardt/temp/craco-esbuild-test/craco.config.js:11:3)
    at configure (/Users/jeffbaumgardt/temp/craco-esbuild-test/craco.config.js:53:29)
    at giveTotalControl (/Users/jeffbaumgardt/temp/craco-esbuild-test/node_modules/@craco/craco/dist/lib/features/webpack/merge-webpack-config.js:76:25)
    at mergeWebpackConfig (/Users/jeffbaumgardt/temp/craco-esbuild-test/node_modules/@craco/craco/dist/lib/features/webpack/merge-webpack-config.js:116:38)
    at overrideWebpackProd (/Users/jeffbaumgardt/temp/craco-esbuild-test/node_modules/@craco/craco/dist/lib/features/webpack/override.js:14:80)
    at /Users/jeffbaumgardt/temp/craco-esbuild-test/node_modules/@craco/craco/dist/scripts/build.js:20:40
npm run build  8.27s user 0.86s system 128% cpu 7.097 total

~/temp/craco-esbuild-test  master ✗                                   3m ⚑ ◒  ⍉
▶
```

I've checked out the existing issues both here and with esbuild-loader and nothing is popping up. 

I can replace just the minimizer with `ESBuildMinifyPlugin` so part of the loader does work. Its just around the line `:48` that it fails.

My ultimate goal here is to replace the babel-loader and terser minimizer. I have a large production app that uses CRA5 and the builds are taking 5m - 10m on a decent machine.

**Comment by JeffBaumgardt** [comment]
It would appear that the `url-loader` is not found in the webpack config. I had to manually run the `addAfterLoader` matches to find that no rules matched. I did find a match for `resolve-url-loader`. It looks like the `url-loader` isn't used in CRA5. Might be able to add a throw of some kind when the `loaderByName` doesn't resolve. The end result is the `isAdded` flag is false and there's no detail as to why it wasn't added.

Now changing my `addAfterLoader` to check for `@svgr/webpack` works, but there's a new error with the configuration object. 

```
Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration.module.rules[1] should be one of these:
   ["..." | object { assert?, compiler?, dependency?, descriptionData?, enforce?, exclude?, generator?, include?, issuer?, issuerLayer?, layer?, loader?, mimetype?, oneOf?, options?, parser?, realResource?, resolve?, resource?, resourceFragment?, resourceQuery?, rules?, scheme?, sideEffects?, test?, type?, use? }, ...]
   -> A rule.
   Details:
    * configuration.module.rules[1].oneOf[2].use[1] has an unknown property 'test'. These properties are valid:
      object { ident?, loader?, options? }
    * configuration.module.rules[1].oneOf[2].use[1] has an unknown property 'include'. These properties are valid:
      object { ident?, loader?, options? }
    * configuration.module.rules[1].oneOf[2].use[2] has an unknown property 'test'. These properties are valid:
      object { ident?, loader?, options? }
    * configuration.module.rules[1].oneOf[2].use[2] has an unknown property 'exclude'. These properties are valid:
      object { ident?, loader?, options? }
```

Namely the the loader use object properties of `test`, `include` and `exclude`. These properties are indeed in the CRA webpack config. - https://github.com/facebook/create-react-app/blob/v5.0.1/packages/react-scripts/config/webpack.config.js#L513

These rule properties are part of the webpack api schema spec as defined [Webpack configuration - Module - Rules](https://webpack.js.org/configuration/module/#modulerules)

I'm unsure of where that error is coming from to be honest. I don't see a stack trace nor do I find that error message in the repo.

I believe this is something to do with webpack 4 and 5 running in the same project. (Webpack 4 is still a dependency of a dependent for babel-loader for instance. However care of CRA I haven't done much direct work with webpack.

**Comment by JeffBaumgardt** [comment]
Yup, man webpack configs api is built very strange, oh well. I found that the `addAfterLoader` and `addBeforeLoader` were only splicing in the same grouping. So in CRA's use case it was in the oneOf block and specifically the `use` object. So the error is correct. The loading I'm adding is esbuild-loader which does have those properties. Then the babel-loader is added back in which also includes those. If I move the loader insertion up in the chain to be inserted at the 0 index the build proceeds. 

Not sure if that's correct. I believe loaders have order. So I'll keep fiddeling.

**Comment by JeffBaumgardt** [comment]
Alright well I think I've got what I needed done. This was my issue in not knowing enough about the internals to know which loaders I should target and where. There might be some handy push/pop loader rule vs find and insert. Also perhaps a easier way to query loaders. Thanks for what you have done here. It's really great work. Being able to modify/extend CRA configs are really nice, not having to eject and manage it all yourself.
