### ISSUE TITLE
captureStackTrace error in 7.0.0-alpha.8

### ISSUE THREAD

**Issue by nmoinvaz** [dilanx/craco#458]
I recently upgraded from 7.0.0-alpha3 and got this error when running `yarn run build`:

```bash
launcher\.pnp.cjs:29601
      Error.captureStackTrace(firstError);
            ^

Error: cosmiconfig-typescript-loader tried to access ts-node (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.


Ancestor breaking the chain: @craco/craco@virtual:ab4c8b1ab99b4c684d1fa26fd7083489156b6cff23e84ce144cdf75e5979801100d1fff80e841f1d23649859adb6b7e066e0feb88a783ca47f3ca335f0b7a5a5#npm:7.0.0-alpha.8


Require stack:
- launcher\.yarn\__virtual__\cosmiconfig-typescript-loader-virtual-ae2ce49d50\0\cache\cosmiconfig-typescript-loader-npm-4.1.1-77b25222d1-a774961868.zip\node_modules\cosmiconfig-typescript-loader\dist\cjs\index.js
- launcher\.yarn\__virtual__\@craco-craco-virtual-ee584bf97f\0\cache\@craco-craco-npm-7.0.0-alpha.8-2ec5b813e5-2fd70bbd5a.zip\node_modules\@craco\craco\dist\lib\config.js
- launcher\.yarn\__virtual__\@craco-craco-virtual-ee584bf97f\0\cache\@craco-craco-npm-7.0.0-alpha.8-2ec5b813e5-2fd70bbd5a.zip\node_modules\@craco\craco\dist\scripts\build.js    at Function.require$$0.Module._resolveFilename (launcher\.pnp.cjs:29601:13)
    at Function.require$$0.Module._load (C:\Users\nathan\Source\skins\launcher\.pnp.cjs:29455:42)    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)    at Object.<anonymous> (launcher\.yarn\__virtual__\cosmiconfig-typescript-loader-virtual-ae2ce49d50\0\cache\cosmiconfig-typescript-loader-npm-4.1.1-77b25222d1-a774961868.zip\node_modules\cosmiconfig-typescript-loader\dist\cjs\index.js:28:22)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.require$$0.Module._extensions..js (launcher\.pnp.cjs:29645:33)    at Module.load (node:internal/modules/cjs/loader:981:32)    at Function.require$$0.Module._load (Clauncher\.pnp.cjs:29485:14)
```

**Comment by dilanx** [comment]
This is the same issue as #447. Check there for updates.
